# Generated by Django 4.1.1 on 2022-11-24 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docname', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('docid', models.IntegerField()),
                ('docadd', models.CharField(max_length=50)),
                ('docnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patname', models.CharField(max_length=50)),
                ('disease', models.CharField(max_length=50)),
                ('patid', models.IntegerField()),
                ('patadd', models.CharField(max_length=50)),
                ('patnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.patient')),
            ],
        ),
    ]
