# Generated by Django 4.1.1 on 2022-11-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patname',
            new_name='patientname',
        ),
    ]
