# Generated by Django 4.1.1 on 2022-11-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_patname_patient_patientname'),
    ]

    operations = [
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('room', models.IntegerField()),
                ('medicine', models.IntegerField()),
                ('other', models.IntegerField()),
            ],
        ),
    ]
